### ISSUE TITLE
Support Azure Artifacts as a core scenario

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PowerShellGet#492]
JavaScript, C#, Java, and Python all have well-defined processes for
* publishing and hosting private modules in Azure Artifacts
* using Azure Artifacts as a secure mirror for public repositories

While there was a recently published [guide](https://devblogs.microsoft.com/powershell/using-powershellget-with-azure-artifacts/) on the subject, I have been unable to get it working (presumably due to #433 ), and even still, there is no information on added PowerShell Gallery as an upstream package source, so there is no way of applying Component Governance to PowerShell modules or avoiding downloading from a public repository, which is forbidden in many security contexts.

Using Azure Artifacts as a private repository and mirror should be a core priority for PowerShellGet, as it enables PowerShell developers to operate at the same pedigree as application developers.  Please use this scenario when prioritizing features and writing documentation.

**Comment by chriskuech** [comment]
If [this](https://github.com/Azure/azure-devops-cli-extension/issues/540) gets implemented, it would be amazing to have PowerShell be securely and automatically configured with just two simple commands.

**Comment by alerickson** [comment]
Hi @chriskuech just finished fixing #433, but could you tell me what issues you're running into in getting it up and running?

**Comment by alerickson** [comment]
Hi @chriskuech the blog post needs to be updated.  You can try testing out the credential provider by registering a repository (right now credentials are not needed [due to PowerShell/PowerShellGetv2#433]).  You can then run Find-Module on that repository.  You'll get prompted for credentials, but you can also set up an [environment variable](https://github.com/Microsoft/artifacts-credprovider#environment-variables) if you want a non-interactive experience.

**Comment by chriskuech** [comment]
Would it be possible to set PowerShell Gallery as a nuget upstream target for my Azure Artifacts feed?  If so, what would be the URL to add as the nuget upstream target?

**Comment by Jaykul** [comment]
I'm sorry, this is rubbish.

We have to provide credentials for every request? Why? Why can't this work like **every other azure CLI tool** and just _cache_ the credential (forever) by default?

**Comment by chriskuech** [comment]
You don't have to "provide credentials for every request".  @alerickson posted a link for setting up non-interactive login in his reply.  It would be nice if it behaved like AzureRM's cred caching though...

**Comment by Jaykul** [comment]
@chriskuech Malarkey. Did you actually get the environment variable to work? 

Here's what happened when I tried: PowerShell/PowerShellGetv2#499

**Comment by alerickson** [comment]
@Jaykul @chriskuech  I just published [PowerShellGet](https://www.poshtestgallery.com/packages/PowerShellGet/2.2) and [PackageManagement](https://www.poshtestgallery.com/packages/PackageManagement/1.4.3) to our int gallery (www.poshtestgallery.com/api/v2). Please feel free to test these out and see if behavior is working appropriately. The credential provider should only be prompted if the -credential parameter is not passed in.

You can register the int gallery and install the respective modules by running:
```
Register-PSRepository -Name PoshTestGallery -SourceLocation https://www.poshtestgallery.com/api/v2
Install-Module PowerShellGet, PackageManagement -Repository PoshTestGallery -Force
```

**Comment by chriskuech** [comment]
so we create a pscredential with a $null username and the PAT token as the password?

**Comment by alerickson** [comment]
@chriskuech you can use the -credential parameter with a pscredential object (with the appropriate username associated with the PAT).  If you don't use the -credential parameter the credential provider will prompt for credentials.

**Comment by chriskuech** [comment]
Sorry I just tried with v2.2.1 and I'm still seeing issues depending on the feed url I use.

```
WARNING: Unable to resolve package source '<feed-url>/index.json'.
```

```
Register-PsRepository : The specified Uri '<feed-url>' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
```
